name: Workflow

on: push

jobs:
  build-workflow:
    runs-on: ubuntu-latest
    container: alpine:latest

    permissions:
      contents: write

    steps:
      - name: Install git
        run: |
          apk add git
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@v4

      - name: Build Assets
        run: |
          apk add bash
          bash build/build_assets.sh

      - name: Build Manifest
        run: |
          apk add python3
          python build/build_manifest.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build Workflow
